### ISSUE TITLE
screenCenter() Error, FlashDevelop

### ISSUE THREAD

**Issue by mhoose** [HaxeFlixel/flixel-tutorial#7]
Everytime I debug the MenuState.hx, it's always halted and gave me error. Saying: "flixel.ui.FlxButton has no field screenCenter"

![screenshot at 05-08-51](https://cloud.githubusercontent.com/assets/8574484/6310278/c776a590-b987-11e4-94ec-becf110d93cf.png)

**Comment by Gama11** [comment]
Similar to #5, you're missing `using flixel.util.FlxSpriteUtil;` (as opposed to `import`). This Haxe feature is called [static extension](http://haxe.org/manual/lf-static-extension.html).
